export const actionTypes = {
  // Login
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS ',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  // Profile
  PROFILE_REQUEST: 'PROFILE_REQUEST',
  PROFILE_SUCCESS: 'PROFILE_SUCCESS',
  PROFILE_FAILURE: 'PROFILE_FAILURE',

  // Events
  EVENT_REQUEST: 'EVENT_REQUEST',
  EVENT_SUCCESS: 'EVENT_SUCCESS',
  EVENT_FAILURE: 'EVENT_FAILURE',

  // NewsFeed
  NEWSFEED_REQUEST: 'NEWSFEED_REQUEST',
  NEWSFEED_SUCCESS: 'NEWSFEED_SUCCESS',
  NEWSFEED_FAILURE: 'NEWSFEED_FAILURE',

  // Edit-Profile
  EDIT_PROFILE_REQUEST: 'EDIT_PROFILE_REQUEST',
  EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
  EDIT_PROFILE_FAILURE: 'EDIT_PROFILE_FAILURE',

  // Notification
  NOTIFICATION_REQUEST: 'NOTIFICATION_REQUEST',
  NOTIFICATION_SUCCESS: 'NOTIFICATION_SUCCESS',
  NOTIFICATION_FAILURE: 'NOTIFICATION_FAILURE',

  // Survey List
  SURVEY_LIST_REQUEST: 'SURVEY_LIST_REQUEST',
  SURVEY_LIST_SUCCESS: 'SURVEY_LIST_SUCCESS',
  SURVEY_LIST_FAILURE: 'SURVEY_LIST_FAILURE',

  // QuickLinks
  QUICK_LINK_REQUEST: 'QUICK_LINK_REQUEST',
  QUICK_LINK_SUCCESS: 'QUICK_LINK_SUCCESS',
  QUICK_LINK_FAILURE: 'QUICK_LINK_FAILURE',

  // Logout
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};
