export const actionTypes = {
  // Login
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS ',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  // Profile
  PROFILE_REQUEST: 'PROFILE_REQUEST',
  PROFILE_SUCCESS: 'PROFILE_SUCCESS',
  PROFILE_FAILURE: 'PROFILE_FAILURE',

  // Events
  EVENT_REQUEST: 'EVENT_REQUEST',
  EVENT_SUCCESS: 'EVENT_SUCCESS',
  EVENT_FAILURE: 'EVENT_FAILURE',
};
