const AppIcons = {
  user: require('../../assets/Icons/user.png'),
  logo: require('../../assets/Icons/logo.png'),
  password: require('../../assets/Icons/password.png'),
  mainLogo: require('../../assets/Icons/mainlogo.png'),
  success: require('../../assets/Icons/check.png'),
  menu: require('../../assets/Icons/menu.png'),
  home: require('../../assets/Icons/home.png'),
  events: require('../../assets/Icons/events.png'),
  profile: require('../../assets/Icons/profile.png'),
  notification: require('../../assets/Icons/notification.png'),
  survey: require('../../assets/Icons/survey.png'),
  quickLinks: require('../../assets/Icons/quickLinks.png'),
  logout: require('../../assets/Icons/logout.png'),
  back: require('../../assets/Icons/backicon.png'),
  call: require('../../assets/Icons/call.png'),
  community: require('../../assets/Icons/community.png'),
  email: require('../../assets/Icons/email.png'),
  location: require('../../assets/Icons/location.png'),
  search: require('../../assets/Icons/search.png'),
  calender: require('../../assets/Icons/calender.png'),
  glass: require('../../assets/Icons/glass.png'),
  document: require('../../assets/Icons/document.png'),
  forward: require('../../assets/Icons/forward.png'),
  send: require('../../assets/Icons/send.png'),
  add: require('../../assets/Icons/add.png'),
};
export default AppIcons;
